export const JOB_LOAD_REQUEST = "JOB_LOAD_REQUEST";
export const JOB_LOAD_SUCCESS = "JOB_LOAD_SUCCESS";
export const JOB_LOAD_FAIL = "JOB_LOAD_FAIL";
export const JOB_LOAD_RESET = "JOB_LOAD_RESET";

export const JOB_LOAD_SINGLE_REQUEST = "JOB_LOAD_SINGLE_REQUEST";
export const JOB_LOAD_SINGLE_SUCCESS = "JOB_LOAD_SINGLE_SUCCESS";
export const JOB_LOAD_SINGLE_FAIL = "JOB_LOAD_SINGLE_FAIL";
export const JOB_LOAD_SINGLE_RESET = "JOB_LOAD_SINGLE_RESET";

export const REGISTER_JOB_REQUEST = "REGISTER_JOB_REQUEST";
export const REGISTER_JOB_SUCCESS = "REGISTER_JOB_SUCCESS";
export const REGISTER_JOB_FAIL = "REGISTER_JOB_FAIL";
export const REGISTER_JOB_RESET = "REGISTER_JOB_RESET";

export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL";
export const DELETE_JOB_RESET = "DELETE_JOB_RESET";

export const ADMIN_JOB_LOAD_REQUEST = "DELETE_JOB_REQUEST";
export const ADMIN_JOB_LOAD_SUCCESS = "DELETE_JOB_SUCCESS";
export const ADMIN_JOB_LOAD_FAIL = "DELETE_JOB_FAIL";
export const ADMIN_JOB_LOAD_RESET = "DELETE_JOB_RESET";

export const EDIT_JOB_REQUEST = "EDIT_JOB_REQUEST";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_FAIL = "EDIT_JOB_FAIL";
export const EDIT_JOB_RESET = "EDIT_JOB_RESET";

export const USER_APPLY_JOB_REQUEST = "USER_APPLY_JOB_REQUEST";
export const USER_APPLY_JOB_SUCCESS = "USER_APPLY_JOB_SUCCESS";
export const USER_APPLY_JOB_FAIL = "USER_APPLY_JOB_FAIL";
export const USER_APPLY_JOB_RESET = "USER_APPLY_JOB_RESET";

export const UPDATE_JOB_REQUEST = "USER_APPLY_JOB_REQUEST";
export const UPDATE_JOB_SUCCESS = "USER_APPLY_JOB_SUCCESS";
export const UPDATE_JOB_FAIL = "USER_APPLY_JOB_FAIL";
export const UPDATE_JOB_RESET = "USER_APPLY_JOB_RESET";

export const SHOW_COMPANY_JOB_REQUEST = "SHOW_COMPANY_JOB_REQUEST";
export const SHOW_COMPANY_JOB_SUCCESS = "SHOW_COMPANY_JOB_SUCCESS";
export const SHOW_COMPANY_JOB_FAIL = "SHOW_COMPANY_JOB_FAIL";
export const SHOW_COMPANY_JOB_RESET = "SHOW_COMPANY_JOB_RESET";
